nome = str(input('Digite seu nome: ')).strip()
print('Vamos analizar seu nome...')
print('Seu nome em maiusculas: {}'.format(nome.upper()))
print('Seu nome em minusculas: {}'.format(nome.lower()))
print('Seu nome possui {} letras'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))
